'use client';

import HeroSection from '@/components/HeroSection';
import { motion } from 'framer-motion';

export default function PrivacyProtocolPage() {
  return (
    <main className="min-h-screen bg-black">
      <HeroSection 
        headline="PRIVACY" 
        subheadline="PROTOCOL" 
        imageSrc="/trans-nzoia-townhall/tnts-image01.jpeg"
      />
      
      <section className="w-full py-32 bg-background relative overflow-hidden px-4">
        <div className="glow-orb -top-20 -right-20 opacity-10"></div>
        <div className="max-w-4xl mx-auto relative z-10">
          <div className="text-[10px] font-black uppercase tracking-[0.2em] text-primary mb-8">Data Governance</div>
          <h2 className="text-5xl font-black mb-16 tracking-tighter italic uppercase underline decoration-primary decoration-4 underline-offset-8">
            Privacy <span className="text-white/20">Protocol</span>
          </h2>
          
          <div className="space-y-12 text-white/60 font-medium text-lg leading-relaxed">
            <div className="modern-card p-10 bg-white/2 border border-white/5">
              <h3 className="text-xl font-black text-white uppercase tracking-tighter mb-4 italic">01. Collective Data Sovereignty</h3>
              <p>
                At VAR 37-38, we believe that data generated by the youth belongs to the youth. Our protocol is designed to protect participants' civic identity while ensuring the movement's integrity.
              </p>
            </div>

            <div className="space-y-8">
              <h3 className="text-2xl font-black text-white uppercase tracking-tighter italic border-l-4 border-primary pl-6">Core Principles</h3>
              <ul className="space-y-6">
                <li className="flex gap-4">
                  <span className="text-primary font-black">/</span>
                  <p><span className="text-white">Anonymity by Default:</span> When participating in general townhalls, individual identities are protected unless explicit consent is provided for leadership roles.</p>
                </li>
                <li className="flex gap-4">
                  <span className="text-primary font-black">/</span>
                  <p><span className="text-white">Secure Gating:</span> Participant data for the "Democracy Activated" registry is stored on encrypted, long-term civic infrastructure powered by Uamuzi.</p>
                </li>
                <li className="flex gap-4">
                  <span className="text-primary font-black">/</span>
                  <p><span className="text-white">Non-Disclosure:</span> VAR 37-38 does not sell, trade, or leak participant data to third-party political actors or corporate entities.</p>
                </li>
              </ul>
            </div>

            <div className="modern-card p-10 bg-white/2 border border-white/5">
              <h3 className="text-xl font-black text-white uppercase tracking-tighter mb-4 italic">02. Usage of Information</h3>
              <p>
                The information collected (Name, Email, Ward, National ID) is strictly for verifying voter eligibility, coordinating ward-level activations, and providing secure access to the VAR digital toolkits.
              </p>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
